spring.application.name=calculator_se_morning

spring.datasource.url=jdbc:posgresqsl://localhost:5432/calc_auth_db
spring.datasource.username=postgres
spring.datasource.password=P4$$w0rd

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true